### PR TITLE
Add warning to the encryption example file

### PR DESCRIPTION
**Pull request by timshadel**
This is an excellent demonstration on how to bring encryption to sembast, but it is an entirely insecure implementation. The encryption is unauthenticated, the password conversion to bytes is massively underpowered (password hashes like bcyrpt, scrypt, argon2id, and pbkdf2 are some examples of correct algorithms), and the random bytes generator doesn't use a cryptographically secure source of randomness. I don't think that you should actually supply a production-ready version of encryption. But this is enough to help anyone see how the pieces should work.

### CODE REVIEW

**Comment by neiljaywarner** [comment]
@timshadel  @timshadel  what if you change this from "/// FOR DEMONSTRATION PURPOSES ONLY -- THIS IMPLEMENTATION IS INSECURE!" to "/// FOR DEMONSTRATION PURPOSES ONLY -- do not use in production as-is!"
or something, and perhaps making an issue for this.

PRs being left open a long tiume contribute to an overall feeling that a package is not well maintained. I get it, there's a reason on this one, it's just free advice.thank you

**Comment by alextekartik** [comment]
Yes I kind of left this on the side because I wanted to properly explained why this is unsecure - sorry I'm not an expert in crypto. Will merge and add some notes. Thanks

**Comment by neiljaywarner** [comment]
Totally Understandable
Thanks for the response

....sent from my phone

**Comment by alextekartik** [comment]
@timshadel @neiljaywarner I have added some notes based on the original comment of the PR, see https://github.com/tekartik/sembast.dart/commit/5b02bf2d6e291b1a3e8405be2e9ab7949427b24f

I hope you're ok with the notice. Thanks!

**Pull request merged**
